# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todos_development
  username: moredream
  password:
  host: /Users/moredream/.nerpa/postgresql/
  port: 5432
  encoding: unicode
  pool: 5
test:
  <<: *default
  database: todos_test
  username: moredream
  password:
  host: /Users/moredream/.nerpa/postgresql/
  port: 5432
  encoding: unicode
  pool: 5


  <<: *default
  database: todos_production
  username: moredream
  password: <%= ENV['TODOS_DATABASE_PASSWORD'] %>
